//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DehouwerDein_a2._1_DM_Project.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertentie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Advertentie()
        {
            this.NieuwsArtikelAdvertentie = new HashSet<NieuwsArtikelAdvertentie>();
        }
    
        public int id { get; set; }
        public string afbeelding { get; set; }
        public string url { get; set; }
        public System.DateTime tijdsduur { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NieuwsArtikelAdvertentie> NieuwsArtikelAdvertentie { get; set; }
    }
}
