//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DehouwerDein_a2._1_DM_Project.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auteur
    {
        public int id { get; set; }
        public int nieuwsArtikelId { get; set; }
        public int gebruikerId { get; set; }
    
        public virtual NieuwsArtikel NieuwsArtikels { get; set; }
        public virtual Gebruiker Gebruikers { get; set; }
    }
}
