//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DehouwerDein_a2._1_DM_Project.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bericht
    {
        public int id { get; set; }
        public string onderwerp { get; set; }
        public int ontvangerId { get; set; }
        public int verstuurderId { get; set; }
        public string inhoud { get; set; }
        public System.DateTime verstuurdOm { get; set; }
    
        public virtual Gebruiker Verstuurder { get; set; }
        public virtual Gebruiker Ontvanger { get; set; }
    }
}
