//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DehouwerDein_a2._1_DM_Project.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NieuwsArtikel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NieuwsArtikel()
        {
            this.Auteur = new HashSet<Auteur>();
            this.Reactie = new HashSet<Reactie>();
        }
    
        public int id { get; set; }
        public string titel { get; set; }
        public int categorieId { get; set; }
        public string artikel { get; set; }
        public System.DateTime aangemaaktOp { get; set; }
        public string samenvatting { get; set; }
        public string cover { get; set; }
        public bool plusArtikel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Auteur> Auteur { get; set; }
        public virtual Categorie Categorie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reactie> Reactie { get; set; }
    }
}
